# Site settings
title: "Jason Resume Template"
description: "This is Amazing."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jian Guo/Jason"
resume_title:                   "Software Engineer"
resume_contact_email:           "jianguo@smu.edu"
resume_contact_telephone:       "1-(310)-592-5325"
resume_contact_address:         "Dallas, Texas"
resume_header_contact_info: "Dallas, Texas | 1-(310)-592-5325 | jianguo@smu.edu"
resume_header_intro: "<p>Software Enginner, passionate about programming.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/OhForReal"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/wobujupa"
  resume_linkedin_url:          "https://www.linkedin.com/in/jian-guo-1b295693/"
  resume_instagram_url:         "https://www.instagram.com/mrblack_jason/"
  #resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

theme: jekyll-theme-architect
